# This is a basic workflow to help you get started with Actions

name: Update Nobl9 SLOS

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request_review:
    types: [submitted]
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
   #The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build Nobl9 sloctl
        run: echo Hello, world!

      # Runs a single command using the runners shell
      - name: Authenticate Secrets
        run: echo Hello, world!
  
      # Runs a single command using the runners shell
      - name: Deploy Updated YAML
        run: echo Hello, world!
